#!/usr/bin/env python3
"""Write docs/BOM-REV-C.md from data/bom-stock.json (tools/bom_stock.py output).

foreman/microduck-assembly.60, 2026-10-10.
"""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    d = json.load(open(os.path.join(HERE, "data", "bom-stock.json")))
    rows = d["rows"]
    cost = sum((r.get("lcsc_usd_10") or 0) * r["qty_per_board"] for r in rows)
    out = ["# Rev C bill of materials, stock checked live", "",
           "foreman/microduck-assembly.60. Generated by `tools/bom_doc.py` from "
           "`data/bom-stock.json`, which `tools/bom_stock.py` fetched from LCSC and the "
           "JLCPCB SMT parts list at **%s** for a build of **%d boards**." % (d["fetched_utc"], d["boards"]), "",
           "JLC stock is what the assembly line places from; LCSC stock is the retail shop. "
           "A line is OK when JLC holds at least the quantity the build needs. "
           "Seven basic parts show 0 at the LCSC shop and hundreds of thousands to millions "
           "at JLC; JLC assembles from its own stock, so they are OK.", "",
           "| refs | qty/board | LCSC | MPN | maker | package | JLC stock | need | LCSC stock | JLC library | USD each (10+) | OK |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append("| %s | %d | [%s](https://www.lcsc.com/product-detail/%s.html) | %s | %s | %s | %s | %d | %s | %s | %s | %s |" % (
            ", ".join(r["refs"]), r["qty_per_board"], r["lcsc"], r["lcsc"], r.get("mpn", ""),
            r.get("brand", ""), r.get("package", ""), "{:,}".format(r.get("jlc_stock") or 0),
            r["need"], "{:,}".format(r.get("lcsc_stock") or 0), r.get("jlc_library", ""),
            "%.4f" % (r.get("lcsc_usd_10") or 0), "yes" if r.get("ok") else "**NO**"))
    short = [r["lcsc"] for r in rows if not r.get("ok")]
    tight = min(rows, key=lambda r: (r.get("jlc_stock") or 0) / r["need"])
    out += ["", "%d lines, %d short. Parts per board at LCSC 10+ prices: **$%.2f**. "
            "Tightest line: %s (%s), JLC stock %s for a need of %d." % (
                len(rows), len(short), cost, tight["lcsc"], ", ".join(tight["refs"]),
                "{:,}".format(tight["jlc_stock"]), tight["need"]), ""]
    open(os.path.join(HERE, "docs", "BOM-REV-C.md"), "w").write("\n".join(out))
    print("%d lines, short %s, $%.2f/board" % (len(rows), short, cost))


if __name__ == "__main__":
    main()
